### ISSUE TITLE
warn users when using wrong database file

### ISSUE THREAD

**Issue by rmflight** [hfang-bristol/dcGOR#1]
Currently, if the user uses the incorrect `RData.HIS` file, it returns NULL instead of warning the user.

For example, if I have PFAM ID's but use:

```
RData.HIS = "Feature2GOMF.sf"
```

A warning should be given that none of the Architecture IDs are present, instead of merely returning NULL.

**Comment by hfang-bristol** [comment]
Thanks for your message. Now warning message is added (see the function '
dcAlgoPredict'). Please also update to the latest version:

library(devtools)
for(pkg in c("dnet","dcGOR")){
    if(pkg %in% rownames(installed.packages())) remove.packages(pkg)
    install_github(repo=paste("hfang-bristol",pkg,sep="/"))
}

Many thanks!

Hai

**Comment by rmflight** [comment]
Thanks Hai, will check into it!
