### ISSUE TITLE
dcEnrichment failing without explanation

### ISSUE THREAD

**Issue by kjohnsen** [hfang-bristol/dcGOR#2]
I tried to run dcEnrichment, but my Eoutput result object getting returned was simply "FALSE". After looking more carefully at the demo (for promiscuous Pfam domains) I noticed that my Pfam domains had the ".x" suffix on them, and after taking them off, everything worked fine. So could you fix it to automatically take that into account? I got my Pfam domains from HMMscan, so I can imagine that format isn't too uncommon.

**Comment by hfang-bristol** [comment]
Thanks for the suggestion. As said, the input must be Pfam identifiers. Now I still keep this requirement so as to make it easier to maintain the software.

**Comment by kjohnsen** [comment]
I mean, my input was Pfam identifiers, and it didn't work. I had "PF12831.6", for example, instead of "PF12831".
