### ISSUE TITLE
Cannot install, 'dnet' dependency problem

### ISSUE THREAD

**Issue by sdeywis** [hfang-bristol/dcGOR#3]
Hi,
I tried to install by:  install.packages("dcGOR")
getting this error:

ERROR: dependencies ‘supraHex’, ‘graph’, ‘Rgraphviz’ are not available for package ‘dnet’
* removing ‘/home/sucharita/R/x86_64-pc-linux-gnu-library/3.3/dnet’
Warning in install.packages :
  installation of package ‘dnet’ had non-zero exit status
ERROR: dependency ‘dnet’ is not available for package ‘dcGOR’
* removing ‘/home/sucharita/R/x86_64-pc-linux-gnu-library/3.3/dcGOR’
Warning in install.packages :
  installation of package ‘dcGOR’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpL9bxkS/downloaded_packages’

Please help. Thanks

**Comment by hfang-bristol** [comment]
Please follow the instruction at http://supfam.org/dcGOR/install.html
In short, it is much easier to install dcGOR and its dependencies from Bioconductor:
source("http://bioconductor.org/biocLite.R")
biocLite(c("supraHex","graph","Rgraphviz","dnet","dcGOR"))

**Comment by sdeywis** [comment]
Successful, thanks.
